### ISSUE TITLE
Definition to handle `.html.erb` file names

### ISSUE THREAD

**Issue by sunny** [malt03/rails-rspec-file-toggle#2]
Hi there! Thank you for the time saved with this extension 🤗 

Is there a way to write a definition that would handle this use-case?

- `app/components/my_component.rb` <=> `spec/components/my_component_spec.rb`
- `app/components/my_component.html.erb` => `spec/components/my_component_spec.rb` (instead of the default `spec/components/payments/stripe_checkout_component.html._spec.rb`)

**Comment by malt03** [comment]
Hi there! Thank you for using the extension and for your kind words 🤗

Unfortunately, in the current state of this project, the use case you're describing cannot be accommodated. Additionally, I am not currently developing in Rails, so I am not actively using or maintaining this extension.

However, if you would like to submit a PR to address this use case, I'd be more than happy to review, merge, and release it.

Thank you for your understanding!

**Comment by malt03** [comment]
@sunny Since I no longer have access to my old Microsoft account, I am publishing the new version using the new org.
[Here](https://marketplace.visualstudio.com/items?itemName=malt-03.rails-rspec-file-toggler) is the URL for the new version.
I have submitted a removal request to Microsoft for the old org and extensions.

**Comment by sunny** [comment]
Thank you @malt03! Installed from the new org, and issue is fixed 🤗
